SSO.Passport.IdentityServer/Controllers/PassportController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using Common;
using IBLL;
using Masuit.Tools;
using Masuit.Tools.Net;
using Masuit.Tools.NoSQL;
using Masuit.Tools.Security;
using Masuit.Tools.Strings;
using Models.Dto;
using Models.Entity;
using Newtonsoft.Json;
using SSO.Core.Client;
using SSO.Core.Server;
using SSO.Passport.IdentityServer.Models.Hangfire;

namespace SSO.Passport.IdentityServer.Controllers
{
    public class PassportController : Controller
    {
        public static RedisHelper RedisHelper { get; set; } = new RedisHelper();
        public IUserInfoBll UserInfoBll { get; set; }
        public ILoginRecordBll LoginRecordBll { get; set; }

        public PassportController(IUserInfoBll userInfoBll, ILoginRecordBll loginRecordBll)
        {
            UserInfoBll = userInfoBll;
            LoginRecordBll = loginRecordBll;
        }

        protected ActionResult ResultData(object data, bool isTrue = true, string message = "")
        {
            return Content(JsonConvert.SerializeObject(new { Success = isTrue, Message = message, Data = data }, new JsonSerializerSettings { MissingMemberHandling = MissingMemberHandling.Ignore }), "application/json");
        }
        public ActionResult PassportCenter()
        {
            //没有授权Token非法访问
            if (string.IsNullOrEmpty(Request["token"]))
            {
                return Content("没有授权Token，非法访问");
            }
            if (Session.GetByCookieRedis<UserInfo>() != null)
            {
                UserInfo userInfo = Session.GetByCookieRedis<UserInfo>();
                return Redirect(PassportService.GetReturnUrl(userInfo.Id.ToString(), Request["token"], Request["returnUrl"]));
            }
            return View();
        }


        /// <summary>
        /// 授权登陆验证
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public ActionResult PassportVertify()
        {
            var cookie = Request.Cookies[Constants.USER_COOKIE_KEY];
            if (cookie == null || string.IsNullOrEmpty(cookie.ToString()))
            {
                return RedirectToAction("Login", new { ReturnUrl = Regex.Replace(Request["ReturnUrl"], @"ticket=(.{0,36})&token=(.{0,32})", String.Empty), Token = Request["Token"] });
            }
            string userId = cookie.Value;
            var success = PassportService.AuthernVertify(Request["Token"], Convert.ToDateTime(Request["TimeStamp"]));
            if (!success)
            {
                return RedirectToAction("Login", new { ReturnUrl = Regex.Replace(Request["ReturnUrl"], @"ticket=(.{0,36})&token=(.{0,32})", String.Empty), Token = Request["Token"] });
            }
            return Redirect(PassportService.GetReturnUrl(userId, Request["Token"], Request["ReturnUrl"]));
        }


        /// <summary>
        /// 登录页
        /// </summary>
        /// <returns></returns>
        public ActionResult Login()
        {
            string from = Request["ReturnUrl"];
            if (!string.IsNullOrEmpty(from))
            {
                from = Server.UrlDecode(from);
                CookieHelper.SetCookie("refer", from);
            }

            if (Session.GetByCookieRedis<UserInfoDto>() != null)
            {
                if (string.IsNullOrEmpty(from))
                {
                    return RedirectToAction("Index", "Home");
                }

                return Redirect(from);
            }

            if (Request.Cookies.Count > 2)
            {
                string name = CookieHelper.GetCookieValue("username");
                string pwd = CookieHelper.GetCookieValue("password")?.DesDecrypt(ConfigurationManager.AppSettings["BaiduAK"]);
                var userInfo = UserInfoBll.Login(name, pwd);
                if (userInfo != null)
                {
                    CookieHelper.SetCookie("username", name, DateTime.Now.AddDays(7));
                    CookieHelper.SetCookie("password", CookieHelper.GetCookieValue("password"), DateTime.Now.AddDays(7));
                    Session.SetByRedis(userInfo);
                    HangfireHelper.CreateJob(typeof(IHangfireBackJob), "LoginRecord", "default", userInfo, Request.UserHostAddress);
                    if (string.IsNullOrEmpty(from))
                    {
                        return RedirectToAction("Index", "Home");
                    }

                    return Redirect(from);
                }
            }

            return View();
        }

        /// <summary>
        /// 登录表单
        /// </summary>
        /// <param name="username">用户名</param>
        /// <param name="password">密码</param>
        /// <param name="valid">验证码</param>
        /// <param name="remem">记住密码</param>
        /// <returns></returns>
        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Login(string username, string password, string valid, string remem)
        {
            string validSession = Session.GetByCookieRedis<string>("valid") ?? String.Empty; //将验证码从Session中取出来，用于登录验证比较
            if (String.IsNullOrEmpty(validSession) || !valid.Trim().Equals(validSession, StringComparison.InvariantCultureIgnoreCase))
            {
                return ResultData(null, false, "验证码错误");
            }

            Session.RemoveByCookieRedis("valid"); //验证成功就销毁验证码Session，非常重要
            if (String.IsNullOrEmpty(username.Trim()) || String.IsNullOrEmpty(password.Trim()))
            {
                return ResultData(null, false, "用户名或密码不能为空");
            }

            var userInfo = UserInfoBll.Login(username, password);
            if (userInfo != null)
            {
                Session.SetByRedis(userInfo);
                if (remem.Trim().Contains(new[] { "on", "true" })) //是否记住登录
                {
                    HttpCookie userCookie = new HttpCookie("username", Server.UrlEncode(username.Trim()));
                    Response.Cookies.Add(userCookie);
                    userCookie.Expires = DateTime.Now.AddDays(7);
                    HttpCookie passCookie = new HttpCookie("password", password.Trim().DesEncrypt(ConfigurationManager.AppSettings["BaiduAK"])) { Expires = DateTime.Now.AddDays(7) };
                    Response.Cookies.Add(passCookie);
                }
#if !DEBUG
                HangfireHelper.CreateJob(typeof(IHangfireBackJob), "LoginRecord", "default", userInfo, Request.UserHostAddress); 
#endif
                string refer = CookieHelper.GetCookieValue("refer");
                if (string.IsNullOrEmpty(refer))
                {
                    return ResultData(null, true, "/");
                }

                return ResultData(null, true, refer);
            }

            return ResultData(null, false, "用户名或密码错误");
        }

        /// <summary>
        /// 生成验证码
        /// </summary>
        /// <returns></returns>
        public ActionResult ValidateCode()
        {
            string code = Masuit.Tools.Strings.ValidateCode.CreateValidateCode(6);
            Session.SetByRedis(code, "valid"); //将验证码生成到Session中
            System.Web.HttpContext.Current.CreateValidateGraphic(code);
            Response.ContentType = "image/jpeg";
            return File(Encoding.UTF8.GetBytes(code), "image/jpeg");
        }

        /// <summary>
        /// 检查验证码
        /// </summary>
        /// <param name="code"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult CheckValidateCode(string code)
        {
            string validSession = Session.GetByCookieRedis<string>("valid");
            if (String.IsNullOrEmpty(validSession) || !code.Trim().Equals(validSession, StringComparison.InvariantCultureIgnoreCase))
            {
                return ResultData(null, false, "验证码错误");
            }

            return ResultData(null, false, "验证码正确");
        }

        /// <summary>
        /// 获取当前登录的用户
        /// </summary>
        /// <returns></returns>
        public ActionResult GetUserInfo()
        {
            UserInfoDto user = Session.GetByCookieRedis<UserInfoDto>();
#if DEBUG
            user = UserInfoBll.GetByUsername("masuit").Mapper<UserInfoDto>();
#endif
            return ResultData(user);
        }

        /// <summary>
        /// 注销
        /// </summary>
        /// <returns></returns>
        public ActionResult Logout()
        {
            Session.RemoveByCookieRedis();
            CookieHelper.SetCookie("username", string.Empty, DateTime.Now.AddDays(-1));
            CookieHelper.SetCookie("password", string.Empty, DateTime.Now.AddDays(-1));
            CookieHelper.SetCookie(Constants.USER_SESSION_KEY, string.Empty, DateTime.Now.AddDays(-1));
            if (Request.HttpMethod.ToLower().Equals("get"))
            {
                return RedirectToAction("Index", "Home");
            }

            return ResultData(null, message: "注销成功！");
        }

        /// <summary>
        /// 注册用户
        /// </summary>
        /// <param name="name"></param>
        /// <param name="email"></param>
        /// <param name="pwd"></param>
        /// <param name="confirm"></param>
        /// <param name="valid"></param>
        /// <returns></returns>
        public ActionResult Register(string name, string email, string pwd, string confirm, string valid)
        {
            string validSession = Session.GetByCookieRedis<string>("valid") ?? String.Empty; //将验证码从Session中取出来，用于登录验证比较
            if (String.IsNullOrEmpty(validSession) || !valid.Trim().Equals(validSession, StringComparison.InvariantCultureIgnoreCase))
            {
                return ResultData(null, false, "验证码错误");
            }

            Session.RemoveByCookieRedis("valid"); //验证成功就销毁验证码Session，非常重要

            if (String.IsNullOrEmpty(name.Trim()))
            {
                return ResultData(null, false, "用户名不能为空");
            }

SSO.Passport.IdentityServer/Views/Passport/Login.cshtml
@{
    ViewBag.Title = "统一登录";
    Layout = null;
}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1,user-scalable=no">
    <title>@ViewBag.Title</title>
    <link href="~/Content/login/style.css" rel="stylesheet"/>
    <link rel="stylesheet" href="~/Content/iconfont.css">
    <script src="~/Scripts/jquery-2.2.4.js"></script>
    <link href="~/Content/jquery-labelauty.css" rel="stylesheet"/>@*单选复选框美化插件*@
    <script src="~/Scripts/jquery.complexify.js"></script>@*密码评级插件*@
    <script src="~/Scripts/jquery.placeholder.min.js"></script>@*密码评级插件*@

    @*背景图片自动更换*@
    <script src="~/Scripts/supersized.3.2.7.min.js"></script>
    <script src="~/Scripts/supersized-init.js"></script>

    @*单选复选框美化插件*@
    <script src="~/Scripts/jquery-labelauty.js"></script>
</head>
<body>
<div class="login-box">
    <div class="box-con tran">
        <form id="login-form" action="" method="POST" onsubmit="return false">
            <div class="login-con f-l">
                <div class="form-group">
                    <header>
                        <h1>用户认证中心登录</h1>
                    </header>
                </div>
                @Html.AntiForgeryToken()
                <div class="form-group">
                    <input type="text" id="username" name="username" placeholder="用户名/邮箱"/>
                    <span class="error-notic">用户名/邮箱不正确</span>
                </div>
                <div class="form-group">
                    <input type="password" name="password" id="password" placeholder="您的密码">
                    <span class="error-notic">用户名或密码不正确</span>
                </div>
                <div class="form-group">
                    <input type="text" placeholder="请输入6位验证码(点击图片刷新验证码)" id="validcode" name="valid" class="valid" maxlength="6" onkeyup="showLoginBtn()">
                    <img class="validcode1" src="/Passport/ValidateCode" style="display: inline">
                    <span class="error-notic">验证码不正确</span>
                </div>
                <ul class="dowebok">
                    <li>
                        <input type="checkbox" name="remem" id="rememberMe" checked data-labelauty="一周内自动登录">
                    </li>
                </ul>
                <div class="form-group" id="btnlogin" style="display: none">
                    <button type="button" class="tran pr" onclick="login()">
                        <a class="tran">登录</a>
                        <img class="loading" id="statues" src="~/Content/images/loading.gif" style="display: none">
                    </button>
                    <span id="loginStatues" class="error-notic">登录失败，请检查表单完整性！</span>
                </div>
            </div>
        </form>
        <!-- 登录 -->
    </div>
</div>
</body>
</html>
<script type="text/javascript">
	$(function() {
		$(':input').labelauty(); //单选复选框美化插件初始化
		$("#loginbtn").click(login); //登录按钮事件
		$(".validcode1").click(flushcode); //刷新验证码

		//绑定各表单事件
		$("#validcode").on("keyup", function(e) {
			if (e.keyCode == 13) {
				//判断回车键
				login();
			}
		}); //验证码
		$("#myPassword").on("change", function(e) {
			document.querySelector("#myPassword2").value = "";
		}); //密码框1内容改变事件

		//表单事件
		$(".signup-form input").on("focus", function() {
			$(this).parent().addClass("border");
		});
		$(".signup-form input").on("blur", function() {
			$(this).parent().removeClass("border");
		});
	});

	//登录过程
    function login() {
        $(".tran").attr({ "disabled": "disabled" });
		$("#statues").fadeIn(100);
		$("#statues").parents("button").parents(".form-group").find(".error-notic").fadeOut(100);
        $.post("/Passport/Login", $("#login-form").serialize(), function (data) {
			if (data.Success) {
                location.href = data.Message || "/Home/Index"; //否则直接跳转
                return;
			} else {
                $("#statues").parents("button").parents(".form-group").find(".error-notic").html(data.Message);
				$("#statues").parents("button").parents(".form-group").find(".error-notic").fadeIn(100);
                $("#statues").fadeOut(200);
                $(".tran").removeAttr("disabled");
                flushcode();
			}
		});
	}

	//刷新验证码
	function flushcode() {
		var code = "/Passport/ValidateCode?" + newGuid();
		$(".validcode1").attr("src", code);
	}

	//创建一个guid值
	function newGuid() {
		var guid = "";
		for (var i = 1; i <= 32; i++) {
			var n = Math.floor(Math.random() * 16.0).toString(16);
			guid += n;
			if ((i == 8) || (i == 12) || (i == 16) || (i == 20)) {
				guid += "-";
			}
		}
		return guid;
	}

	//检查验证码
	function CheckValidCode(_this) {
		var code = $(_this).val();
		$.post("/Passport/CheckValidateCode", {
			"code": code
		}, function(data) {
			if (data.Success) {
				hideNotic(_this);
			} else {
				$(_this).parents(".form-group").find(".error-notic").fadeIn(100);
			}
		});
	}

	var _handle = ''; //储存电话是否填写正确

	//表单验证
	function showNotic(_this) {
		$(_this).parents(".form-group").find(".error-notic").fadeIn(100);
		$(_this).focus();
	} //错误提示显示

	function hideNotic(_this) {
		$(_this).parents(".form-group").find(".error-notic").fadeOut(100);
	} //错误提示隐藏

	var verify = {
		VerifyCount: function(_this) {
			var _count = "123456";
			var _value = $(_this).val();
			console.log(_value);
			if (_value != _count) {
				showNotic(_this);
			} else {
				hideNotic(_this);
			}
		}, //验证验证码

	}

	//显示登录按钮
	function showLoginBtn() {
		if ($(".valid").val().length >= 3) {
			$("#btnlogin").fadeIn(1000);
		} else {
			$("#btnlogin").fadeOut(1000);
		}
	}
</script>

SSO.Passport.IdentityServer/Views/Passport/PassportCenter.cshtml
@{
    ViewBag.Title = "统一登录中心";
}
<script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js"></script>
<form id="passport" action="@Url.Action("PassportVertify", "Passport")" method="post">
    @Html.Hidden("ReturnUrl", Request["ReturnUrl"])
    @Html.Hidden("Token", Request["Token"])
    @Html.Hidden("TimeStamp", Request["TimeStamp"])
    @*请求地址：@Request["ReturnUrl"] <br />
        请求Token：@Request["Token"]<br />
        请求时间戳：@Request["TimeStamp"]<br />
        <input type="submit" id="btn" name="authern" value="授权登陆" />*@
</form>
<script type="text/javascript">
    $("#passport").submit();
</script>